/* SUBHA BILLING completion pack */
const _go=window.go;
window.go=async p=>p==='purchase'?purchasePage():p==='settings'?settingsEnhanced():_go(p);
async function purchasePage(){const [a,s,p]=await Promise.all([api('/purchases'),api('/suppliers'),api('/products')]);state.suppliers=s;state.products=p;$('#content').innerHTML=header('Purchase',`<button class="btn primary" onclick="newPurchase()">＋ New Purchase</button>`)+`<div class="panel"><div class="toolbar"><b>Purchase Register</b><button class="btn" onclick="window.open('/api/export/purchases.csv?token='+token,'_blank')">Export CSV</button></div><div class="tablewrap"><table class="table"><thead><tr><th>No.</th><th>Date</th><th>Supplier</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.purchase_no}</td><td>${x.created_at}</td><td>${x.supplier||'—'}</td><td>${money(x.total)}</td><td>${money(x.paid)}</td><td>${money(x.total-x.paid)}</td><td>${x.status}</td><td><button class="btn" onclick="viewPurchase(${x.id})">View</button> <button class="btn" onclick="purchasePayment(${x.id})">Payment</button> <button class="btn danger" onclick="deletePurchase(${x.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
let purchaseRows=[];
function purchaseModal(){const s=state.suppliers,p=state.products;$('#modalbox').innerHTML=`<div class="toolbar"><h3>New Purchase</h3><button class="btn" onclick="closeModal()">×</button></div><div class="formgrid"><div class="field"><label>Supplier</label><select id="ps"><option value="">Walk-in Supplier</option>${s.map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}</select></div><div class="field"><label>Paid</label><input id="pp" type="number" value="0"></div><div class="field"><label>Payment Mode</label><select id="pm"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option><option>Credit</option></select></div></div><table class="invoice-items"><thead><tr><th>Product</th><th>Qty</th><th>Rate</th><th>GST%</th><th></th></tr></thead><tbody>${purchaseRows.map((r,i)=>`<tr><td><select onchange="purchaseRows[${i}].product_id=this.value;purchaseRows[${i}].rate=+this.selectedOptions[0].dataset.r;purchaseRows[${i}].gst=+this.selectedOptions[0].dataset.g;purchaseModal()">${p.map(x=>`<option value="${x.id}" data-r="${x.purchase_price}" data-g="${x.gst}" ${x.id==r.product_id?'selected':''}>${x.name}</option>`).join('')}</select></td><td><input type="number" step=".01" value="${r.qty}" onchange="purchaseRows[${i}].qty=+this.value"></td><td><input type="number" step=".01" value="${r.rate}" onchange="purchaseRows[${i}].rate=+this.value"></td><td><input type="number" step=".01" value="${r.gst}" onchange="purchaseRows[${i}].gst=+this.value"></td><td><button class="btn danger" onclick="purchaseRows.splice(${i},1);purchaseModal()">×</button></td></tr>`).join('')}</tbody></table><button class="btn" onclick="purchaseRows.push({product_id:state.products[0]?.id||'',qty:1,rate:state.products[0]?.purchase_price||0,gst:state.products[0]?.gst||0});purchaseModal()">＋ Add Item</button><button class="btn primary" onclick="savePurchase()" style="margin-left:8px">Create Purchase</button>`;openModal()}
async function newPurchase(){await Promise.all([api('/suppliers').then(x=>state.suppliers=x),api('/products').then(x=>state.products=x)]);purchaseRows=[{product_id:state.products[0]?.id||'',qty:1,rate:state.products[0]?.purchase_price||0,gst:state.products[0]?.gst||0}];purchaseModal()}
async function savePurchase(){try{await api('/purchases',{method:'POST',body:JSON.stringify({supplier_id:$('#ps').value||null,paid:+$('#pp').value||0,payment_mode:$('#pm').value,items:purchaseRows})});closeModal();toast('Purchase created');purchasePage()}catch(e){alert(e.message)}}
async function viewPurchase(id){const p=await api('/purchases/'+id);$('#modalbox').innerHTML=`<div class="toolbar"><h3>${p.purchase_no}</h3><button class="btn" onclick="closeModal()">Close</button></div><p><b>Supplier:</b> ${p.supplier}</p><table class="table"><thead><tr><th>Product</th><th>Qty</th><th>Rate</th><th>GST</th><th>Total</th></tr></thead><tbody>${p.items.map(x=>`<tr><td>${x.name}</td><td>${x.qty}</td><td>${money(x.rate)}</td><td>${x.gst}%</td><td>${money(x.total)}</td></tr>`).join('')}</tbody></table><p style="text-align:right"><b>Total ${money(p.total)}</b><br>Paid ${money(p.paid)}<br>Balance ${money(p.total-p.paid)}</p>`;openModal()}
async function purchasePayment(id){const p=await api('/purchases/'+id);$('#modalbox').innerHTML=`<div class="toolbar"><h3>Purchase Payment</h3><button class="btn" onclick="closeModal()">×</button></div><p>Balance: <b>${money(p.total-p.paid)}</b></p><div class="field"><label>Amount</label><input id="ppa" type="number"></div><div class="field"><label>Mode</label><select id="ppm"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option></select></div><div class="field"><label>Reference</label><input id="ppr"></div><button class="btn primary" onclick="savePurchasePayment(${id})">Save Payment</button>`;openModal()}
async function savePurchasePayment(id){try{await api('/purchases/'+id+'/payment',{method:'POST',body:JSON.stringify({amount:+$('#ppa').value||0,mode:$('#ppm').value,reference:$('#ppr').value})});closeModal();purchasePage();toast('Payment recorded')}catch(e){alert(e.message)}}
async function deletePurchase(id){if(!confirm('Delete purchase and reverse stock?'))return;try{await api('/purchases/'+id,{method:'DELETE'});purchasePage();toast('Purchase deleted')}catch(e){alert(e.message)}}

window.billing=async function(){const a=await api('/invoices');state.invoices=a;$('#content').innerHTML=header('Sales / Billing',`<button class="btn primary" onclick="newInvoice()">＋ New Invoice</button>`)+`<div class="panel"><div class="toolbar"><b>Invoices</b><button class="btn" onclick="downloadCSV()">Export CSV</button></div><div class="tablewrap"><table class="table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th>Action</th></tr></thead><tbody>${a.map(i=>`<tr><td>${i.invoice_no}</td><td>${i.created_at}</td><td>${i.customer}</td><td>${money(i.total)}</td><td>${money(i.paid)}</td><td>${money(i.total-i.paid)}</td><td>${i.status}</td><td><button class="btn" onclick="viewInvoice(${i.id})">View</button> <button class="btn" onclick="editInvoice(${i.id})">Edit</button> <button class="btn danger" onclick="deleteInvoice(${i.id})">Delete</button></td></tr>`).join('')}</tbody></table></div></div>`}
let editRows=[],editInvoiceData=null;
async function editInvoice(id){const [i,c,p]=await Promise.all([api('/invoices/'+id),api('/customers'),api('/products')]);state.customers=c;state.products=p;editInvoiceData=i;editRows=i.items.map(x=>({product_id:x.product_id,qty:x.qty,rate:x.rate,discount:x.discount||0}));renderEdit()}
function renderEdit(){$('#modalbox').innerHTML=`<div class="toolbar"><h3>Edit ${editInvoiceData.invoice_no}</h3><button class="btn" onclick="closeModal()">×</button></div><div class="formgrid"><div class="field"><label>Customer</label><select id="ec"><option value="">Walk-in Customer</option>${state.customers.map(x=>`<option value="${x.id}" ${x.id==editInvoiceData.customer_id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="field"><label>Tax Type</label><select id="et"><option value="LOCAL">CGST + SGST</option><option value="IGST">IGST</option></select></div><div class="field"><label>Discount</label><input id="ed" type="number" value="${editInvoiceData.discount||0}"></div><div class="field"><label>Paid</label><input id="ep" type="number" value="${editInvoiceData.paid||0}"></div><div class="field"><label>Payment Mode</label><select id="em"><option>Cash</option><option>UPI</option><option>Bank</option><option>Card</option><option>Credit</option></select></div></div><table class="invoice-items"><thead><tr><th>Product</th><th>Qty</th><th>Rate</th><th>Discount</th><th></th></tr></thead><tbody>${editRows.map((r,i)=>`<tr><td><select onchange="editRows[${i}].product_id=this.value;editRows[${i}].rate=+this.selectedOptions[0].dataset.r;renderEdit()">${state.products.map(x=>`<option value="${x.id}" data-r="${x.sale_price}" ${x.id==r.product_id?'selected':''}>${x.name}</option>`).join('')}</select></td><td><input type="number" step=".01" value="${r.qty}" onchange="editRows[${i}].qty=+this.value"></td><td><input type="number" step=".01" value="${r.rate}" onchange="editRows[${i}].rate=+this.value"></td><td><input type="number" step=".01" value="${r.discount}" onchange="editRows[${i}].discount=+this.value"></td><td><button class="btn danger" onclick="editRows.splice(${i},1);renderEdit()">×</button></td></tr>`).join('')}</tbody></table><button class="btn" onclick="editRows.push({product_id:state.products[0]?.id||'',qty:1,rate:state.products[0]?.sale_price||0,discount:0});renderEdit()">＋ Add Item</button><button class="btn primary" onclick="saveEditedInvoice()" style="margin-left:8px">Save Changes</button>`;openModal()}
async function saveEditedInvoice(){try{await api('/invoices/'+editInvoiceData.id,{method:'PUT',body:JSON.stringify({customer_id:$('#ec').value||null,tax_type:$('#et').value,discount:+$('#ed').value||0,paid:+$('#ep').value||0,payment_mode:$('#em').value,items:editRows})});closeModal();billing();toast('Invoice updated')}catch(e){alert(e.message)}}
async function deleteInvoice(id){if(!confirm('Delete invoice and reverse stock?'))return;try{await api('/invoices/'+id,{method:'DELETE'});billing();toast('Invoice deleted')}catch(e){alert(e.message)}}

function settingsEnhanced(){$('#content').innerHTML=header('Settings')+`<div class="panel"><div class="formgrid">${[['business_name','Business Name'],['tagline','Tagline'],['gstin','GSTIN'],['address','Business Address'],['phone','Phone'],['email','Email'],['website','Website'],['invoice_prefix','Invoice Prefix'],['state','State'],['bank_name','Bank Name'],['bank_account','A/c Number'],['ifsc','IFSC Code'],['branch','Bank Branch']].map(f=>`<div class="field"><label>${f[1]}</label><input id="s_${f[0]}" value="${state.settings[f[0]]||''}"></div>`).join('')}</div><button class="btn primary" onclick="saveSettings()">Save Settings</button></div><div class="panel" style="margin-top:16px"><h3>Security</h3><div class="formgrid"><div class="field"><label>Current Password</label><input id="oldpw" type="password"></div><div class="field"><label>New Password</label><input id="newpw" type="password"></div><div class="field"><label>Confirm Password</label><input id="newpw2" type="password"></div></div><button class="btn primary" onclick="changePassword()">Change Password</button></div><div class="panel" style="margin-top:16px"><h3>Backup & Restore</h3><button class="btn" onclick="window.open('/api/backup?token='+token,'_blank')">Download Backup</button> <input id="bf" type="file" accept=".json,application/json"> <button class="btn danger" onclick="restoreBackup()">Restore Backup</button></div>`}
async function changePassword(){if($('#newpw').value!==$('#newpw2').value)return alert('Passwords do not match');try{await api('/change-password',{method:'POST',body:JSON.stringify({current_password:$('#oldpw').value,new_password:$('#newpw').value})});toast('Password changed')}catch(e){alert(e.message)}}
async function restoreBackup(){const f=$('#bf').files[0];if(!f)return alert('Select backup JSON');if(!confirm('Restore will replace current data. Continue?'))return;try{await api('/restore',{method:'POST',body:await f.text()});alert('Backup restored. Reloading...');location.reload()}catch(e){alert(e.message)}}
window.gst=async function(){const a=await api('/reports/gst');$('#content').innerHTML=header('GST Reports',`<button class="btn" onclick="window.open('/api/export/gst.csv?token='+token,'_blank')">Export GST CSV</button>`)+`<div class="panel"><table class="table"><thead><tr><th>Date</th><th>Taxable</th><th>CGST</th><th>SGST</th><th>IGST</th><th>Total</th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.date}</td><td>${money(x.taxable)}</td><td>${money(x.cgst)}</td><td>${money(x.sgst)}</td><td>${money(x.igst)}</td><td>${money(x.total)}</td></tr>`).join('')}</tbody></table></div>`}

/* GST RATE DROPDOWN FOR ADD/EDIT PRODUCT */
window.openProduct=function(id){
  const p=id?state.products.find(x=>x.id==id):{};
  const gstRates=[0,5,12,18,28,40];
  $('#modalbox').innerHTML=
    '<div class="toolbar"><h3>'+(id?'Edit':'Add')+' Product</h3><button class="btn" onclick="closeModal()">×</button></div>'+
    '<div class="formgrid">'+
    [['name','Product Name'],['sku','SKU'],['barcode','Barcode'],['category','Category'],['unit','Unit'],['hsn','HSN/SAC'],['purchase_price','Purchase Price'],['sale_price','Sale Price']].map(f=>'<div class="field"><label>'+f[1]+'</label><input id="p_'+f[0]+'" value="'+(p[f[0]]??'')+'"></div>').join('')+
    '<div class="field"><label>GST %</label><select id="p_gst">'+gstRates.map(r=>'<option value="'+r+'" '+(Number(p.gst||0)===r?'selected':'')+'>'+r+'%</option>').join('')+'</select></div>'+
    '<div class="field"><label>Opening Stock</label><input id="p_stock" value="'+(p.stock??'')+'"></div>'+
    '<div class="field"><label>Minimum Stock</label><input id="p_min_stock" value="'+(p.min_stock??'')+'"></div>'+
    '</div><button class="btn primary" onclick="saveProduct('+(id||0)+')">Save Product</button>';
  openModal();
};

/* GST RATE DROPDOWN FOR ADD/EDIT PRODUCT */
window.openProduct=function(id){const p=id?state.products.find(x=>x.id==id):{};const rates=[0,5,12,18,28,40];$('#modalbox').innerHTML='<div class="toolbar"><h3>'+(id?'Edit':'Add')+' Product</h3><button class="btn" onclick="closeModal()">×</button></div><div class="formgrid">'+[['name','Product Name'],['sku','SKU'],['barcode','Barcode'],['category','Category'],['unit','Unit'],['hsn','HSN/SAC'],['purchase_price','Purchase Price'],['sale_price','Sale Price']].map(f=>'<div class="field"><label>'+f[1]+'</label><input id="p_'+f[0]+'" value="'+(p[f[0]]??'')+'"></div>').join('')+'<div class="field"><label>GST %</label><select id="p_gst">'+rates.map(r=>'<option value="'+r+'" '+(Number(p.gst||0)===r?'selected':'')+'>'+r+'%</option>').join('')+'</select></div><div class="field"><label>Opening Stock</label><input id="p_stock" value="'+(p.stock??'')+'"></div><div class="field"><label>Minimum Stock</label><input id="p_min_stock" value="'+(p.min_stock??'')+'"></div></div><button class="btn primary" onclick="saveProduct('+(id||0)+')">Save Product</button>';openModal()};

/* SUBHA BILLING defaults: open new invoice with the permanent school customer selected. */
const _subhaOriginalNewInvoice=window.newInvoice;
window.newInvoice=async function(){
  if(typeof _subhaOriginalNewInvoice==='function'){
    await _subhaOriginalNewInvoice();
    const c=(state.customers||[]).find(x=>x.name==='MAHUR HIGH SECONDARY SCHOOL');
    const sel=$('#icust');
    if(c&&sel) sel.value=String(c.id);
  }
};

/* Show that product sale prices are GST-inclusive in the invoice workflow. */
const _subhaOriginalSaveProduct=window.saveProduct;
window.saveProduct=async function(id){
  return _subhaOriginalSaveProduct(id);
};
