const express=require('express');
const path=require('path');
const Database=require('better-sqlite3');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||'subha-billing-change-me';
const db=new Database(process.env.DB_PATH||path.join(__dirname,'subha-billing.db'));
db.pragma('journal_mode = WAL');
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT DEFAULT 'admin',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT);
CREATE TABLE IF NOT EXISTS customers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,address TEXT,gstin TEXT,state TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS suppliers(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,phone TEXT,address TEXT,gstin TEXT,state TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,sku TEXT UNIQUE,barcode TEXT UNIQUE,category TEXT,unit TEXT DEFAULT 'PCS',hsn TEXT,purchase_price REAL DEFAULT 0,sale_price REAL DEFAULT 0,gst REAL DEFAULT 18,stock REAL DEFAULT 0,min_stock REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS invoices(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_no TEXT UNIQUE NOT NULL,customer_id INTEGER,subtotal REAL DEFAULT 0,discount REAL DEFAULT 0,taxable REAL DEFAULT 0,cgst REAL DEFAULT 0,sgst REAL DEFAULT 0,igst REAL DEFAULT 0,roundoff REAL DEFAULT 0,total REAL DEFAULT 0,paid REAL DEFAULT 0,status TEXT DEFAULT 'Pending',payment_mode TEXT DEFAULT 'Cash',notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id));
CREATE TABLE IF NOT EXISTS invoice_items(id INTEGER PRIMARY KEY AUTOINCREMENT,invoice_id INTEGER,product_id INTEGER,name TEXT,qty REAL,rate REAL,gst REAL,discount REAL DEFAULT 0,taxable REAL,tax REAL,total REAL,FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS purchases(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_no TEXT UNIQUE NOT NULL,supplier_id INTEGER,total REAL DEFAULT 0,paid REAL DEFAULT 0,status TEXT DEFAULT 'Pending',notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(supplier_id) REFERENCES suppliers(id));
CREATE TABLE IF NOT EXISTS purchase_items(id INTEGER PRIMARY KEY AUTOINCREMENT,purchase_id INTEGER,product_id INTEGER,qty REAL,rate REAL,gst REAL,total REAL,FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS payments(id INTEGER PRIMARY KEY AUTOINCREMENT,customer_id INTEGER,invoice_id INTEGER,amount REAL,mode TEXT,reference TEXT,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(customer_id) REFERENCES customers(id),FOREIGN KEY(invoice_id) REFERENCES invoices(id));
`);
const defaults={business_name:'SUBHA BILLING',tagline:'Smart Billing. Premium Business.',gstin:'',address:'',phone:'',email:'',invoice_prefix:'INV',state:'Maharashtra'};
const insSet=db.prepare('INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)'); for(const [k,v] of Object.entries(defaults)) insSet.run(k,v);
const adminEmail=process.env.ADMIN_EMAIL||'admin@subhabilling.com';
if(!db.prepare('SELECT id FROM users WHERE email=?').get(adminEmail)){db.prepare('INSERT INTO users(name,email,password,role) VALUES(?,?,?,?)').run('Admin',adminEmail,bcrypt.hashSync(process.env.ADMIN_PASSWORD||'ChangeMe123!',10),'admin');}
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
function auth(req,res,next){const h=req.headers.authorization||'';const t=h.startsWith('Bearer ')?h.slice(7):(req.query.token||'');if(!t)return res.status(401).json({error:'Login required'});try{req.user=jwt.verify(t,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Session expired'})}}
function settings(){return Object.fromEntries(db.prepare('SELECT key,value FROM settings').all().map(x=>[x.key,x.value]));}
function nextNo(prefix){const row=db.prepare('SELECT invoice_no FROM invoices ORDER BY id DESC LIMIT 1').get();let n=1;if(row){const m=row.invoice_no.match(/(\d+)$/);if(m)n=Number(m[1])+1;}return `${prefix||'INV'}-${new Date().getFullYear()}-${String(n).padStart(6,'0')}`}
function recalcStatus(total,paid){return paid>=total-0.01?'Paid':paid>0?'Partial':'Pending'}
app.post('/api/login',(req,res)=>{const {email,password}=req.body;const u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password,u.password))return res.status(401).json({error:'Invalid email or password'});res.json({token:jwt.sign({id:u.id,name:u.name,email:u.email,role:u.role},JWT_SECRET,{expiresIn:'7d'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user,settings:settings()}));
app.get('/api/dashboard',auth,(req,res)=>{const sales=db.prepare("SELECT COALESCE(SUM(total),0) v FROM invoices WHERE date(created_at)=date('now','localtime')").get().v;const purchases=db.prepare("SELECT COALESCE(SUM(total),0) v FROM purchases WHERE date(created_at)=date('now','localtime')").get().v;const customers=db.prepare('SELECT COUNT(*) v FROM customers').get().v;const pending=db.prepare("SELECT COALESCE(SUM(total-paid),0) v FROM invoices WHERE total>paid").get().v;const low=db.prepare('SELECT COUNT(*) v FROM products WHERE stock<=min_stock').get().v;const recent=db.prepare('SELECT i.*,COALESCE(c.name,"Walk-in Customer") customer FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ORDER BY i.id DESC LIMIT 8').all();const lowItems=db.prepare('SELECT * FROM products WHERE stock<=min_stock ORDER BY stock ASC LIMIT 8').all();const top=db.prepare('SELECT p.name,SUM(ii.qty) qty,SUM(ii.total) amount FROM invoice_items ii JOIN products p ON p.id=ii.product_id GROUP BY ii.product_id ORDER BY amount DESC LIMIT 5').all();const chart=db.prepare("SELECT substr(created_at,1,10) day,ROUND(SUM(total),2) total FROM invoices WHERE created_at>=date('now','-6 day','localtime') GROUP BY day ORDER BY day").all();res.json({sales,purchases,customers,pending,low,recent,lowItems,top,chart});});
app.get('/api/settings',auth,(req,res)=>res.json(settings()));
app.put('/api/settings',auth,(req,res)=>{const data=req.body||{};const q=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');const tx=db.transaction(()=>Object.entries(data).forEach(([k,v])=>q.run(k,String(v??''))));tx();res.json(settings())});
function crud(table,fields){app.get('/api/'+table,auth,(req,res)=>res.json(db.prepare(`SELECT * FROM ${table} ORDER BY id DESC`).all()));app.post('/api/'+table,auth,(req,res)=>{try{const vals=fields.map(f=>req.body[f]??'');const r=db.prepare(`INSERT INTO ${table}(${fields.join(',')}) VALUES(${fields.map(()=>'?').join(',')})`).run(...vals);res.json(db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(r.lastInsertRowid))}catch(e){res.status(400).json({error:e.message})}});app.put('/api/'+table+'/:id',auth,(req,res)=>{try{const sets=fields.map(f=>`${f}=?`).join(',');db.prepare(`UPDATE ${table} SET ${sets} WHERE id=?`).run(...fields.map(f=>req.body[f]??''),req.params.id);res.json(db.prepare(`SELECT * FROM ${table} WHERE id=?`).get(req.params.id))}catch(e){res.status(400).json({error:e.message})}});app.delete('/api/'+table+'/:id',auth,(req,res)=>{try{db.prepare(`DELETE FROM ${table} WHERE id=?`).run(req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}})}
crud('customers',['name','phone','address','gstin','state']);crud('suppliers',['name','phone','address','gstin','state']);crud('products',['name','sku','barcode','category','unit','hsn','purchase_price','sale_price','gst','stock','min_stock']);
app.get('/api/invoices',auth,(req,res)=>res.json(db.prepare('SELECT i.*,COALESCE(c.name,"Walk-in Customer") customer FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id ORDER BY i.id DESC').all()));
app.get('/api/invoices/:id',auth,(req,res)=>{const invoice=db.prepare('SELECT i.*,COALESCE(c.name,"Walk-in Customer") customer,c.phone,c.address,c.gstin,c.state FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE i.id=?').get(req.params.id);if(!invoice)return res.status(404).json({error:'Invoice not found'});invoice.items=db.prepare(`
SELECT
  ii.*,
  COALESCE(p.unit,'PCS') AS unit,
  COALESCE(p.hsn,'-') AS hsn,
  COALESCE(p.gst,ii.gst,0) AS gst
FROM invoice_items ii
LEFT JOIN products p
  ON p.id=ii.product_id
WHERE ii.invoice_id=?
`).all(req.params.id);res.json(invoice)});
app.post('/api/invoices',auth,(req,res)=>{try{const body=req.body, items=body.items||[];if(!items.length)throw Error('Add at least one item');const s=settings();const no=body.invoice_no||nextNo(s.invoice_prefix);let subtotal=0,taxable=0,cgst=0,sgst=0,igst=0;const prepared=[];for(const x of items){const p=db.prepare('SELECT * FROM products WHERE id=?').get(x.product_id);if(!p)throw Error('Product not found');const qty=Number(x.qty)||0,rate=Number(x.rate??p.sale_price)||0,disc=Number(x.discount)||0;const base=Math.max(0,qty*rate-disc),tax=base*Number(p.gst||0)/100;subtotal+=qty*rate;taxable+=base;prepared.push({p,qty,rate,disc,base,tax});}const interState=body.tax_type==='IGST';if(interState)igst=prepared.reduce((a,x)=>a+x.tax,0);else {cgst=prepared.reduce((a,x)=>a+x.tax/2,0);sgst=cgst;}const discount=Number(body.discount)||0;taxable=Math.max(0,taxable-discount);const totalRaw=taxable+cgst+sgst+igst;const total=Math.round(totalRaw);const roundoff=total-totalRaw;const paid=Math.max(0,Number(body.paid)||0);const status=recalcStatus(total,paid);const tx=db.transaction(()=>{const r=db.prepare(`INSERT INTO invoices(invoice_no,customer_id,subtotal,discount,taxable,cgst,sgst,igst,roundoff,total,paid,status,payment_mode,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(no,body.customer_id||null,subtotal,discount,taxable,cgst,sgst,igst,roundoff,total,paid,status,body.payment_mode||'Cash',body.notes||'');const iid=r.lastInsertRowid;const ii=db.prepare('INSERT INTO invoice_items(invoice_id,product_id,name,qty,rate,gst,discount,taxable,tax,total) VALUES(?,?,?,?,?,?,?,?,?,?)');const up=db.prepare('UPDATE products SET stock=stock-? WHERE id=?');for(const x of prepared){ii.run(iid,x.p.id,x.p.name,x.qty,x.rate,x.p.gst,x.disc,x.base,x.tax,x.base+x.tax);up.run(x.qty,x.p.id);}if(paid>0)db.prepare('INSERT INTO payments(customer_id,invoice_id,amount,mode,note) VALUES(?,?,?,?,?)').run(body.customer_id||null,iid,paid,body.payment_mode||'Cash','Invoice payment');return iid;});const iid=tx();res.json({id:iid,invoice_no:no,total,status})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/invoices/:id/payment',auth,(req,res)=>{const inv=db.prepare('SELECT * FROM invoices WHERE id=?').get(req.params.id);if(!inv)return res.status(404).json({error:'Invoice not found'});const amount=Number(req.body.amount)||0;if(amount<=0)return res.status(400).json({error:'Invalid amount'});const paid=inv.paid+amount;db.prepare('UPDATE invoices SET paid=?,status=? WHERE id=?').run(paid,recalcStatus(inv.total,paid),inv.id);db.prepare('INSERT INTO payments(customer_id,invoice_id,amount,mode,reference,note) VALUES(?,?,?,?,?,?)').run(inv.customer_id,inv.id,amount,req.body.mode||'Cash',req.body.reference||'',req.body.note||'');res.json({paid,status:recalcStatus(inv.total,paid)})});
app.get('/api/payments',auth,(req,res)=>res.json(db.prepare('SELECT p.*,COALESCE(c.name,"Walk-in Customer") customer,i.invoice_no FROM payments p LEFT JOIN customers c ON c.id=p.customer_id LEFT JOIN invoices i ON i.id=p.invoice_id ORDER BY p.id DESC').all()));
app.get('/api/reports/sales',auth,(req,res)=>{const from=req.query.from||'2000-01-01',to=req.query.to||'2999-12-31';const rows=db.prepare("SELECT substr(i.created_at,1,10) date,COUNT(*) invoices,ROUND(SUM(i.subtotal),2) subtotal,ROUND(SUM(i.discount),2) discount,ROUND(SUM(i.cgst+i.sgst+i.igst),2) tax,ROUND(SUM(i.total),2) total,ROUND(SUM(i.paid),2) paid FROM invoices i WHERE date(i.created_at) BETWEEN ? AND ? GROUP BY date ORDER BY date DESC").all(from,to);res.json(rows)});
app.get('/api/reports/gst',auth,(req,res)=>res.json(db.prepare("SELECT substr(created_at,1,10) date,ROUND(SUM(taxable),2) taxable,ROUND(SUM(cgst),2) cgst,ROUND(SUM(sgst),2) sgst,ROUND(SUM(igst),2) igst,ROUND(SUM(total),2) total FROM invoices GROUP BY date ORDER BY date DESC").all()));
app.get('/api/export/invoices.csv',auth,(req,res)=>{const rows=db.prepare('SELECT invoice_no,created_at,customer_id,subtotal,discount,taxable,cgst,sgst,igst,roundoff,total,paid,status,payment_mode FROM invoices ORDER BY id DESC').all();const esc=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv=[Object.keys(rows[0]||{invoice_no:1}).join(','),...rows.map(r=>Object.values(r).map(esc).join(','))].join('\n');res.setHeader('Content-Type','text/csv');res.setHeader('Content-Disposition','attachment; filename="subha-billing-invoices.csv"');res.send(csv)});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`SUBHA BILLING running on http://localhost:${PORT}`));

require('./server-enhancements')(app,db,auth,settings,nextNo,bcrypt);
